FROM node:20-alpine

WORKDIR /opt/app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN npm run build && npm prune --omit=dev

ENV NODE_ENV=production
EXPOSE 1337

CMD ["npm", "run", "start"]